import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="fixed top-0 left-0 w-full bg-white shadow-md p-4 z-50 text-center space-x-6">
          <a href="/">Home</a>
          <a href="/Grades">Grades</a>
          <a href="/Goals">Goals</a>
          <a href="/Calendar">Calendar</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
